# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-10-09 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='upload_img/nothing.jpg', upload_to='upload_img/')),
            ],
        ),
        migrations.DeleteModel(
            name='ActivityImage',
        ),
    ]
